### PR TITLE
Update to nightly

### PR DESCRIPTION
**Pull request by fire**
See the commit logs. 

Feel free to edit my branch.

* Upgrade to the latest godot-sandbox nightly.
* Namespace the game portion of the demo. Sandbox paths hardcode their path. Move `scenes` to `slide_knight/scenes` and move `assets` to `slide_knight/art`because asset can refer to everything in the project.
* Add {} to for loops
* Add nearest texture snapping for labels.

### CODE REVIEW

**Comment by fwsGonzo** [comment]
Is this updated to the latest version now?

**Comment by fire** [comment]
Need to update to https://github.com/libriscv/godot-sandbox/commit/78e95276675270560d92acd58a2da410ef02b0da

**Comment by fire** [comment]
Need to update to https://github.com/libriscv/godot-sandbox/commit/7c5e7ec732552454ad2c4abf5002e0f9022aac09

**Comment by fwsGonzo** [comment]
I've added you to the repo now, so feel free to merge whenever it's ready

**Comment by fire** [comment]
Need to update to https://github.com/libriscv/godot-sandbox/releases/tag/v0.12

**Comment by fire** [comment]
Initial update is broken. 

```
docker stop godot-cpp-compiler
docker rm godot-cpp-compiler
docker stop godot-rust-compiler
docker rm godot-rust-compiler
docker pull ghcr.io/libriscv/cpp_compiler
docker pull ghcr.io/libriscv/rust_compiler
```

**Comment by fire** [comment]
Failing on the macos.

**Comment by fire** [comment]
image

**Comment by fwsGonzo** [comment]
I think that might be a rebuild issue? If you rebuild some programs and reload the editor does it start working again?

**Comment by fire** [comment]
https://github.com/libriscv/godot-sandbox/pull/77 may be buggy?

**Pull request merged**
